# Generated by Django 4.2.9 on 2024-01-17 22:55

import certification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('certification_id', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('tags', models.ManyToManyField(to='certification.language')),
            ],
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('badge', models.ImageField(null=True, upload_to=certification.models.badgepic)),
                ('url', models.URLField()),
                ('tags', models.ManyToManyField(to='certification.language')),
            ],
        ),
    ]
