# Generated by Django 4.2.9 on 2024-01-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
