# Generated by Django 4.2.9 on 2024-01-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_education_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
