# Generated by Django 4.2.9 on 2024-01-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='admindata',
            name='interests',
            field=models.ManyToManyField(to='users.areaofinterest'),
        ),
    ]
